version: "3.9"

services:
  influxdb:
    container_name: influxdb
    image: influxdb:1.8.10
    restart: always
    privileged: true
    ports:
      - 8086:8086
      - 8083:8083
    env_file:
      - .env
    volumes:
      - ./docker/influx/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    environment:
      INFLUXDB_DB: linky
      DOCKER_INFLUXDB_CONFIG_PATH: /etc/influxdb/influxdb.conf
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: $INFLUXDB_USERNAME
      DOCKER_INFLUXDB_INIT_PASSWORD: $INFLUXDB_PASSWORD
      DOCKER_INFLUXDB_INIT_ORG: $INFLUXDB_ORG
      DOCKER_INFLUXDB_INIT_BUCKET: $INFLUXDB_BUCKET
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: $INFLUXDB_TOKEN

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:main
    restart: always
    privileged: true
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - influxdb
    volumes:
      - ./docker/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./docker/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./docker/grafana/dashboard.json:/var/lib/grafana/dashboards/dashboard.json
    environment:
      GF_SECURITY_ADMIN_USER: $GRAFANA_ADMIN_USER
      GF_SECURITY_ADMIN_PASSWORD: $GRAFANA_ADMIN_PASSWORD
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "/var/lib/grafana/dashboards/dashboard.json"
      INFLUXDB_URL: $INFLUXDB_URL
      INFLUXDB_TOKEN: $INFLUXDB_TOKEN
      INFLUXDB_ORG: $INFLUXDB_ORG
      INFLUXDB_BUCKET: $INFLUXDB_BUCKET
